# Webserver container
version: '3.5'

services:
  caddy:
    image: caddy:2.3.0-alpine
    ports:
      # HTTP
      - target: 80
        published: ${NGINX_HTTP_PORT:-8081}
        protocol: tcp
      # HTTPS
      - target: 80
        published: ${NGINX_HTTPS_PORT:-8444}
        protocol: tcp
